jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: SonarCloud Scan
      run: 'mvn -B clean --file pom.xml

        mvn -B install sonar:sonar -Dsonar.projectKey=cats -Dsonar.organization=en-milie
        -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

        '
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
