jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Set projects Maven version to GitHub Action GUI set version
      run: mvn versions:set "-DnewVersion=${{ github.event.inputs.releaseversion }}"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Build with Maven
      run: 'mvn -B clean --file pom.xml

        mvn -B package --file pom.xml -DskipTests=true

        '
    - continue-on-error: true
      name: Set up Apache Maven Central
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.GPG_SIGN_KEY }}
        java-version: '17'
        server-id: ossrh
        server-password: MAVEN_CENTRAL_TOKEN
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      env:
        MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGN_PASSPHRASE }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME}}
      name: Publish to Apache Maven Central
      run: mvn -B deploy -Psign --file pom.xml
name: Release to Maven Central
on:
  repository_dispatch:
    types: trigger-ga___release-to-maven-central.yml
